config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/restaurants', to: 'restaurants#index'

  get '/restaurants/new', to: 'restaurants#new', as: :new_restaurant
  post '/restaurants', to: 'restaurants#create'

  get '/restaurants/:id', to: 'restaurants#show', as: :restaurant

  get '/restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant
  patch '/restaurants/:id', to: 'restaurants#update'

  delete '/restaurants/:id', to: 'restaurants#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant.id)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :rating %>
<%= f.number_field :rating %>
<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit this restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>See all our restaurants:</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
     <!-- `restaurant` is an instance of our Restaurant class! -->
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>


<%= link_to 'Add a new restaurant', restaurants_new_path %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>


<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Details about <%= @restaurant.name %></h1>

<p>Address: <%= @restaurant.address %></p>
<p>Rating: <%= @restaurant.rating %></p>

<!-- you can use `lt` + tab for short to get the link_to helper -->
<%= link_to 'Edit this restaurant', edit_restaurant_path(@restaurant)  %>
<%= link_to 'Delete this restaurant', restaurant_path(@restaurant), method: :delete  %>
<%= link_to 'All restaurants', restaurants_path  %>